services:
  - type: web
    name: yc-launch-monitor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn yc_launch_monitor.pond.server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: POND_ACCESS_KEY
        value: kYmQRiFJfVDdzl0ESFa4TvghaNpSBUDR
      - key: POLL_INTERVAL_HOURS
        value: "8"
